#!/usr/bin/env bash

homeconfigdir="$HOME/.config/home-manager"
profilepath="$homeconfigdir/.profile"

get_configs() {
  nix eval --json --apply builtins.attrNames "$homeconfigdir#homeConfigurations" | jq -r '.[]' || true
}

save_profile() {
  echo $profile > $profilepath
}

load_profile() {
  profile=$(head -n 1 $profilepath)
}

get_profile() {
  profile=$(gum choose $(get_configs))
}

main() {
  if [ $0 == "hmpr" ]; then # running hmpr directly should switch profiles manually, usually run via hmsw
    get_profile
    save_profile
  fi
  [ -e $HOME/.config/home-manager/.profile ] && load_profile
  [ ! -e $HOME/.config/home-manager/.profile ] && get_profile
  home-manager switch -b hmbak --flake $HOME/.config/home-manager\#$profile
}
main
