#!/usr/bin/env bash

homeconfigdir="$HOME/.config/home-manager"
profilepath="$homeconfigdir/.profile"
flakeUri="$HOME/.config/home-manager"

get_configs() {
  nix eval --json --apply builtins.attrNames "$homeconfigdir#homeConfigurations" | jq -r '.[]' || echo "Failed to get home-manager profiles"
}

save_profile() {
  echo $profile > $profilepath
}

load_profile() {
  [ -n $HMPROFILE ] && { profile=$HMPROFILE; return; }
  #[ -e $HOME/.config/home-manager/.profile ] && [ ! -z $HMPROFILE ] && { profile=$HMPROFILE; return; }
  [ -e $HOME/.config/home-manager/.profile ] && { profile=$(head -n 1 $profilepath); return; }
  { echo "Failed to load profile, make sure $homeconfigdir/.profile exists or set env: HMPROFILE"; exit 1; }
}

get_profile() {
  profile=$(gum choose --header "Choose your profile: " $(get_configs))
}

main() {

  [ -d $homeconfigdir ] || mkdir -p $homeconfigdir

  # set flake Uri
  [ ! -d $HOME/.config/home-manager ] && flakeUri="https://github.com/kr-nn/nix/archive/home.zip"

  # set Profile
  if [ ! -z $HMPROFILE ] || [ -e $profilepath ]; then
    load_profile
  elif [ ! -e $profilepath ] && [ -z $HMPROFILE ]; then
    get_profile
  fi

  # check if we want to override profile
  while getopts "c" opt; do
    case $opt in
      c) override="yes";;
    esac
  done
  [ ! -z $override ] && get_profile

  [ -z $profile ] && { echo "No profile selected"; exit 1; }
  save_profile
  home-manager switch -b hmbak --flake $flakeUri\#$profile
}
main
