#!/usr/bin/env bash

# shellcheck disable=SC2046
homeconfigdir="$HOME/.config/home-manager"
profilepath="$homeconfigdir/.profile"
flakeUri="$HOME/.config/home-manager"

get_configs() {
  nix eval --json --apply builtins.attrNames "$flakeUri#homeConfigurations" | jq -r '.[]' || echo "Failed to get home-manager profiles"
}

save_profile() {
  echo "$profile" > "$profilepath"
}

load_profile() {
  if [ -n "${HMPROFILE+x}" ]; then
    [ -n "$HMPROFILE" ] && { profile="$HMPROFILE"; return; }
    [ -e "$profilepath" ] && { profile=$(head -n 1 "$profilepath"); return; }
  fi
  return 1
}

get_profile() {
  profile=$(gum choose --header "Choose your profile: " $(get_configs))
}

main() {

  [ -d "$homeconfigdir" ] || mkdir -p "$homeconfigdir"

  # Set flake Uri
  [ ! -d "$homeconfigdir" ] && flakeUri="https://github.com/kr-nn/nix/archive/home.zip"

  if ! load_profile; then
    get_profile
  fi


  [ -z "$profile" ] && { echo "No profile selected"; exit 1; }
  save_profile
  home-manager switch -b hmbak --flake "$flakeUri#$profile"
}
main
